
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.25.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Turbulence.TGUI {
    using System;
    using Terminal.Gui;
    
    
    public partial class Main : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme tgDefault;
       
        
        private Terminal.Gui.FrameView serverView;
        
        private Terminal.Gui.TreeView serverTree;
        
        private Terminal.Gui.FrameView messageView;
        
        private Terminal.Gui.TextView messages;
        
        private Terminal.Gui.FrameView textInputView;
        
        private Terminal.Gui.TextField textInput;
        
        private Terminal.Gui.Button sendButton;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem fileMenu;
        
        private Terminal.Gui.MenuItem quitMenuItem;
        
        private Terminal.Gui.MenuBarItem discordMenu;
        
        private Terminal.Gui.MenuItem setTokenMenuItem;
        
        private Terminal.Gui.MenuBarItem statusMenu; 
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.sendButton = new Terminal.Gui.Button();
            this.textInput = new Terminal.Gui.TextField();
            this.textInputView = new Terminal.Gui.FrameView();
            this.messages = new Terminal.Gui.TextView();
            this.messageView = new Terminal.Gui.FrameView();
            this.serverTree = new Terminal.Gui.TreeView();
            this.serverView = new Terminal.Gui.FrameView();
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Blue);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.ColorScheme = this.tgDefault;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.White;
            this.Border.Background = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Press Ctrl+Q to quit";
            this.serverView.Width = 25;
            this.serverView.Height = Dim.Fill(0);
            this.serverView.X = 0;
            this.serverView.Y = 1;
            this.serverView.Visible = true;
            this.serverView.Data = "serverView";
            this.serverView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.serverView.Border.Effect3D = false;
            this.serverView.Border.Effect3DBrush = null;
            this.serverView.Border.DrawMarginFrame = true;
            this.serverView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.serverView.Title = "Servers";
            this.Add(this.serverView);
            this.serverTree.Width = Dim.Fill(0);
            this.serverTree.Height = Dim.Fill(0);
            this.serverTree.X = 0;
            this.serverTree.Y = 0;
            this.serverTree.Visible = true;
            this.serverTree.Data = "serverTree";
            this.serverTree.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.serverTree.Style.CollapseableSymbol = '-';
            this.serverTree.Style.ColorExpandSymbol = false;
            this.serverTree.Style.ExpandableSymbol = '+';
            this.serverTree.Style.InvertExpandSymbolColors = false;
            this.serverTree.Style.LeaveLastRow = false;
            this.serverTree.Style.ShowBranchLines = true;
            this.serverView.Add(this.serverTree);
            this.messageView.Width = 93;
            this.messageView.Height = 24;
            this.messageView.X = 25;
            this.messageView.Y = 1;
            this.messageView.Visible = true;
            this.messageView.Data = "messageView";
            this.messageView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.messageView.Border.Effect3D = false;
            this.messageView.Border.Effect3DBrush = null;
            this.messageView.Border.DrawMarginFrame = true;
            this.messageView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.messageView.Title = "Messages";
            this.Add(this.messageView);
            this.messages.Width = Dim.Fill(0);
            this.messages.Height = Dim.Fill(0);
            this.messages.X = 0;
            this.messages.Y = 0;
            this.messages.Visible = true;
            this.messages.ColorScheme = this.tgDefault;
            this.messages.AllowsTab = true;
            this.messages.AllowsReturn = true;
            this.messages.WordWrap = false;
            this.messages.Data = "messages";
            this.messages.Text = "";
            this.messages.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.messageView.Add(this.messages);
            this.textInputView.Width = 93;
            this.textInputView.Height = 3;
            this.textInputView.X = 25;
            this.textInputView.Y = 25;
            this.textInputView.Visible = true;
            this.textInputView.Data = "textInputView";
            this.textInputView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.textInputView.Border.Effect3D = false;
            this.textInputView.Border.Effect3DBrush = null;
            this.textInputView.Border.DrawMarginFrame = true;
            this.textInputView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.textInputView.Title = "Write Message";
            this.Add(this.textInputView);
            this.textInput.Width = Dim.Fill(9);
            this.textInput.Height = 1;
            this.textInput.X = 0;
            this.textInput.Y = 0;
            this.textInput.Visible = true;
            this.textInput.Secret = false;
            this.textInput.Data = "textInput";
            this.textInput.Text = "";
            this.textInput.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.textInputView.Add(this.textInput);
            this.sendButton.Width = 8;
            this.sendButton.Height = 1;
            this.sendButton.X = 83;
            this.sendButton.Y = 0;
            this.sendButton.Visible = true;
            this.sendButton.Data = "sendButton";
            this.sendButton.Text = "Send";
            this.sendButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.sendButton.IsDefault = false;
            this.textInputView.Add(this.sendButton);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 1;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.Visible = true;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.fileMenu = new Terminal.Gui.MenuBarItem();
            this.fileMenu.Title = "_File";
            this.quitMenuItem = new Terminal.Gui.MenuItem();
            this.quitMenuItem.Title = "Quit";
            this.quitMenuItem.Data = "quitMenuItem";
            this.fileMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.quitMenuItem};
            this.discordMenu = new Terminal.Gui.MenuBarItem();
            this.discordMenu.Title = "_Discord";
            this.setTokenMenuItem = new Terminal.Gui.MenuItem();
            this.setTokenMenuItem.Title = "Set Token";
            this.setTokenMenuItem.Data = "setTokenMenuItem";
            this.discordMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.setTokenMenuItem};
            this.statusMenu = new Terminal.Gui.MenuBarItem();
            this.statusMenu.Title = "Not Connected";
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileMenu,
                    this.discordMenu,
                    this.statusMenu};
            this.Add(this.menuBar);
        }
    }
}
